import { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import styled from 'styled-components';
import PageHeader from '../../components/PageHeader';
import TextField from '../../components/Signup/TextField';
import SignUpTitle from '../../components/Signup/SignUpTitle';
import NavButton from '../../components/Signup/NavButton';
import SignUpChangeIcon from '../../assets/icons/SignUpChange.svg';
import { isGuestSession, getStoredNickname, getStoredSlug } from '../../utils/guestSession';

const FieldsContainer = styled.div`
  display: flex;
  flex-direction: column;
  gap: 12px;
`;

// 랜덤 닉네임 생성 함수
const generateRandomNickname = () => {
  const adjectives = [
    '멋진', '귀여운', '행복한', '빛나는', '용감한', '똑똑한', '친절한', '활발한',
    '차분한', '밝은', '강한', '부드러운', '따뜻한', '시원한', '신비로운', '재미있는', 
    '화려한', '우아한', '자유로운', '열정적인', '평화로운', '즐거운', '기쁜', '사랑스러운',
    '아름다운', '순수한', '깨끗한', '새로운', '신선한', '특별한', '독특한', '창의적인',
    '영리한', '빠른', '느긋한', '조용한', '명랑한'
  ];
  
  const nouns = [
    '고양이', '강아지', '토끼', '햄스터', '다람쥐', '팬더', '곰', '펭귄',
    '돌고래', '나비', '별', '달', '구름', '바람', '물결', '꽃',
    '나무', '산', '바다', '하늘', '별빛', '햇살', '달빛', '무지개',
    '사자', '호랑이', '코끼리', '기린', '얼룩말', '원숭이', '캥거루', '코알라',
    '여우', '늑대', '사슴', '말', '소', '양', '염소', '돼지',
    '닭', '오리', '거위', '백조', '도마뱀'
  ];

  const randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomNoun = nouns[Math.floor(Math.random() * nouns.length)];
  
  return `${randomAdjective} ${randomNoun}`;
};

export default function Nickname({ userName = '숨쉬는 고양이' }) {
  const navigate = useNavigate();
  const location = useLocation();
  
  // 게스트→회원 전환 시 에러 메시지 및 이전 닉네임 확인
  const fromGuest = location.state?.fromGuest === true;
  const errorMessage = location.state?.errorMessage || '';
  const previousNickname = location.state?.previousNickname || '';
  const nicknameFromState = location.state?.nickname || '';
  const slugFromState = location.state?.slug;
  
  // 백엔드 로직: upgradeGuestToUser에서 게스트의 UserFestival을 새 User로 소유권 변경
  // 게스트 닉네임을 그대로 사용하면 백엔드에서 통과 (festival.getNickname().equals(newNickname))
  // localStorage에서 자동 생성된 닉네임 확인 (비로그인 상태에서만)
  const getAutoGeneratedNickname = () => {
    // state에서 전달된 닉네임이 있으면 우선 사용 (게스트 닉네임)
    if (nicknameFromState) {
      return nicknameFromState;
    }
    
    // 에러로 돌아온 경우 이전 닉네임 사용
    if (previousNickname) {
      return previousNickname;
    }
    
    if (isGuestSession()) {
      return getStoredNickname();
    }

    const isLoggedIn = localStorage.getItem('isLoggedIn') === 'true';
    if (!isLoggedIn) {
      return getStoredNickname();
    }

    return '';
  };
  
  const autoNickname = getAutoGeneratedNickname();
  
  const [formData, setFormData] = useState({
    nickname: autoNickname || '',
  });
  
  // 에러 메시지가 있으면 초기화 시 표시
  const [showError, setShowError] = useState(!!errorMessage);

  const handleBack = () => {
    navigate('/login');
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    // 입력 시 에러 메시지 숨김
    if (showError) {
      setShowError(false);
    }
  };

  const handleRandomNickname = () => {
    const randomNickname = generateRandomNickname();
    setFormData((prev) => ({
      ...prev,
      nickname: randomNickname,
    }));
  };

  const isAllFieldsFilled = formData.nickname.trim() !== '';

  const handleNext = () => {
    if (isAllFieldsFilled) {
      // 백엔드: upgradeGuestToUser에서 slug 필요 (게스트의 UserFestival 조회)
      // 백엔드: festival.getNickname().equals(newNickname) 체크를 위해 정확히 일치해야 함
      // trim()은 하되, 원본 닉네임과 정확히 일치하도록 보장
      const slug = slugFromState || getStoredSlug('line4thon');
      const nicknameToSend = formData.nickname.trim();
      navigate('/signup/email', {
        state: {
          nickname: nicknameToSend,
          fromGuest: fromGuest,
          slug: slug,
        }
      });
    }
  };

  return (
    <div>
      <PageHeader title="회원가입" onBack={handleBack} />
      <SignUpTitle 
        title={
          <>
            PLINK에서 사용할<br />
            멋진 닉네임을 알려주세요!
          </>
        }
      />
      <FieldsContainer>
        <TextField
          name="nickname"
          placeholder={`${userName}`}
          helperText={
            showError && errorMessage 
              ? errorMessage 
              : fromGuest 
                ? '게스트 로그인 시 사용한 닉네임입니다. 변경하려면 수정해주세요.' 
                : '닉네임을 입력해주세요.'
          }
          value={formData.nickname}
          onChange={handleChange}
          icon={SignUpChangeIcon}
          onIconClick={handleRandomNickname}
        />

          </FieldsContainer>
      <NavButton isActive={isAllFieldsFilled} onClick={handleNext}>다음 단계로(1/2)</NavButton></div>
  );
}
